# Generated by Django 4.0.6 on 2022-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
